package com.github.seratch.signedrequest4j.pem;

import com.github.seratch.signedrequest4j.pem.DerParser.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
public class DerParserTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(DerParser.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		InputStream in = null;
		DerParser target = new DerParser(in);
		assertThat(target, notNullValue());
	}

	@Test
	public void read_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		InputStream in = null;
		DerParser target = new DerParser(in);
		// given
		// e.g. : given(mocked.called()).willReturn(1);
		// when
		Asn1Object actual = target.read();
		// then
		// e.g. : verify(mocked).called();
		Asn1Object expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

}
