package com.github.seratch.signedrequest4j.pem;

import com.github.seratch.signedrequest4j.pem.PEMReader.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import com.github.seratch.signedrequest4j.Base64;
import java.io.*;
public class PEMReaderTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(PEMReader.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		InputStream inStream = null;
		PEMReader target = new PEMReader(inStream);
		assertThat(target, notNullValue());
	}

	@Test
	public void readFile_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		InputStream inStream = null;
		PEMReader target = new PEMReader(inStream);
		// given
		// e.g. : given(mocked.called()).willReturn(1);
		// when
		target.readFile();
		// then
		// e.g. : verify(mocked).called();
	}

}
