package com.github.seratch.signedrequest4j.pem;

import com.github.seratch.signedrequest4j.pem.PKCS1EncodedKeySpec.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;
import static org.mockito.BDDMockito.*;

import java.io.IOException;
import java.math.BigInteger;
import java.security.spec.RSAPrivateCrtKeySpec;
public class PKCS1EncodedKeySpecTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(PKCS1EncodedKeySpec.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		byte[] keyBytes = null;
		PKCS1EncodedKeySpec target = new PKCS1EncodedKeySpec(keyBytes);
		assertThat(target, notNullValue());
	}

}
