package com.github.seratch.signedrequest4j;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;


public class OAuthServiceProviderTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(OAuthServiceProvider.class);
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		String requestTokenURL = null;
		String userAuthorizationURL = null;
		String accessTokenURL = null;
		OAuthServiceProvider target = new OAuthServiceProvider(requestTokenURL, userAuthorizationURL, accessTokenURL);
		assertNotNull(target);
	}

	@Test
	public void getAccessTokenURL_A$() throws Exception {
		String requestTokenURL = null;
		String userAuthorizationURL = null;
		String accessTokenURL = "ac";
		OAuthServiceProvider target = new OAuthServiceProvider(requestTokenURL, userAuthorizationURL, accessTokenURL);
		String actual = target.getAccessTokenURL();
		String expected = "ac";
		assertEquals(expected, actual);
	}

	@Test
	public void getRequestTokenURL_A$() throws Exception {
		String requestTokenURL = "req";
		String userAuthorizationURL = null;
		String accessTokenURL = null;
		OAuthServiceProvider target = new OAuthServiceProvider(requestTokenURL, userAuthorizationURL, accessTokenURL);
		String actual = target.getRequestTokenURL();
		String expected = "req";
		assertEquals(expected, actual);
	}

	@Test
	public void getUserAuthorizationURL_A$() throws Exception {
		String requestTokenURL = null;
		String userAuthorizationURL = "auth";
		String accessTokenURL = null;
		OAuthServiceProvider target = new OAuthServiceProvider(requestTokenURL, userAuthorizationURL, accessTokenURL);
		String actual = target.getUserAuthorizationURL();
		String expected = "auth";
		assertEquals(expected, actual);
	}

}
